<?php 
session_start();
$includes="./includes/";
include_once($includes.'header.php');
include_once('./home.php');
include_once('./nav.php');
include_once('./about.php');
include_once('./studies.php');
include_once('./works.php');
include_once('./contact.php');
include_once($includes.'footer.php');
?>